### ISSUE TITLE
你好，我这边怎么打不到文中所述效果呢

### ISSUE THREAD

**Issue by guanyonglai** [djidje/D-MMD#3]
duke迁移到market的结果：
mAP: 47.4%
CMC curve
Rank-1  : 68.7%
Rank-5  : 85.7%
Rank-10 : 91.0%
Rank-20 : 94.4%

**Comment by djidje** [comment]
Hi,

you can try increasing the batch size to 128.

I put it to 32 to allow person with only 1 GPU to run the experiments.

Don't forget to uncomment the line :
```py
model = nn.DataParallel(model).cuda()
```
